env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - freebsd
      - windows
    goarch:
      - amd64
archives:
  - format: zip
    name_template: "{{ .ProjectName }}-cli-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    files:
      - README.md
release:
  github:
    owner: guitmz
    name: transferwise
  name_template: "{{.Version}}"
changelog:
  sort: asc
  filters:
    exclude:
    - "typo"
    - "^docs:"
    - "^test:"
checksum:
  name_template: "checksums.txt"
brews:
  -
    tap:
      owner: guitmz
      name: homebrew-tools
    homepage: "https://github.com/guitmz/transferwise"
    description: "A transferwise command line tool"
    license: "MIT"
    test: |
      system "#{bin}/transferwise", "--version" 